name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Definir variáveis de ambiente para o hash do commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Construir e Publicar Imagem
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rafaeldemiranda/techchallenge-producao:${{ env.COMMIT_HASH }}
